# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
  ["Trial - Post Conviction_DESCRIPTION GOES HERE ", 
    "Trial_DESCRIPTION GOES HERE", 
    "Post Conviction_DESCRIPTION GOES HERE"].each do |t|
    role, description = t.chomp.split("_")
    CaseRole.find_or_create_by_role(:role => role, :description => description)
  end
  
  ["Vietnam",
  "Victim Advocate",
  "Venue/Polling",
  "Undue Influence/Cults",
  "Traffic",
  "Toxicology",
  "Tires",
  "Substance Abuse",
  "Strickland",
  "Statistics & Demographics",
  "Speech Science & Audio Tape Analysis",
  "SPECT/ PET Scans",
  "Soil",
  "Social History",
  "Sleep Disorders",
  "Shaken Baby Syndrome",
  "Sex Crimes",
  "Sex Abuse",
  "Serology",
  "Serial Killers",
  "Sentencing/Juvenile Justice",
  "San Quentin",
  "Religion",
  "Rape",
  "Radiology",
  "PTSD/Vietnam",
  "PTSD",
  "Psychopharmacology",
  "Psychology Consultant",
  "Prison/Corrections/Institutionalization",
  "Polygraph/Reid Method",
  "Polygraph",
  "Police/Gangs",
  "Police Procedures",
  "Pharmacokinetics",
  "Pediatric Neurology",
  "Pediatric",
  "Pathology",
  "Orthopedics",
  "Ophthalmology",
  "Odontologist",
  "Numismatics",
  "Neurology",
  "Necrophilia",
  "Native American Studies",
  "Molecular Immunology",
  "MMPI",
  "Mitigation Specialist",
  "Mental Retardation/Intellectual Disability",
  "Memory/Eyewitness Testimony",
  "Memory",
  "Linguistics and Cultural Forensics",
  "Lethal Injection",
  "Latino Mental Health",
  "Knives",
  "Juvenile Justice",
  "Jury",
  "Investigator",
  "Interpreter - Vietnamese",
  "Interpreter - Spanish",
  "Interpreter - Samoan",
  "Interpreter - Mandarin",
  "Interpreter - Laotion",
  "Interpreter - Khmer/Cambodian",
  "Interpreter - Farsi",
  "Interpreter - Cantonese",
  "Interpreter - Arabic",
  "Internal Medicine",
  "Insects",
  "Identification",
  "Hypnotist",
  "Handwriting/Document Examiner",
  "Handwriting",
  "Gunshot Residue",
  "Genetics",
  "Gangs",
  "Forensics",
  "Forensic Pediatric Pathology",
  "Forensic Hypnosis",
  "Fire-Arson",
  "Fingerprints",
  "FAS",
  "False Confessions/Police Interrogation",
  "Eyewitness Identification/Memory",
  "Eyewitness Identification",
  "Estonian Comparative Folklore",
  "Estonia Archives/History",
  "Emotional Intelligence",
  "Emergency Room",
  "Electrical/Chemical",
  "Education",
  "Economics",
  "Drugs",
  "DNA",
  "Developmental Disabilities",
  "Culture - Latino",
  "Culture - Asian",
  "Culture",
  "Crime Scene Reconstruction",
  "Crime Scene Investigation",
  "Coercive Control",
  "Cell Phone Tracking",
  "Ballistics/Firearms"].each do |t|
    name = t
    Specialty.find_or_create_by_name(:name => name, :description => "DESCRIPTION GOES HERE")
  end

  ["Toxicology_",
  "Speech-Language Pathology_",
  "Sociology_",
  "Social Work_",
  "Public Administration_",
  "Psychometrics_",
  "Psychology_",
  "Psychiatry_",
  "Physician_",
  "Pharmacology_",
  "Neuroscience_",
  "Neuropsychology_",
  "Neuropsychiatry_",
  "Neurology_",
  "Mitigation_",
  "Martial Arts_",
  "Linguistics_",
  "Law Enforcement_",
  "Jury_",
  "Investigator_",
  "Interpreter/Translators_",
  "Geology_",
  "Geography_",
  "Forensic Science_",
  "Forensic Pathology_",
  "Entomology_",
  "Engineering_",
  "Dentistry_",
  "Culture_",
  "Computer Science_",
  "Chemistry_",
  "Certified Public Accountant_",
  "Botany_",
  "Biology_",
  "Biochemistry_",
  "Attorney_",
  "Anthropology_",
    ].each do |t|
    name, description = t.chomp.split("_")
    Credential.find_or_create_by_name(:name => name, :description => description)
  end