source 'http://rubygems.org'

gem 'rails', '3.2.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'


gem 'mysql2'
gem 'execjs'
gem 'therubyracer', '~> 0.10.2'
#gem 'libv8', '~> 3.11.8'
gem 'bcrypt-ruby', :require => "bcrypt"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.2.3"
  gem 'coffee-rails', "~> 3.2.1"
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end

#Tire client to use ElasticSearch
gem 'tire'
gem 'ransack'

#Paperclip for file attachments. documents being attached to entries.
#gem "paperclip"

gem 'formtastic'

#getting smtp working with cap's exchange server
gem 'mail'
gem 'ruby-ntlm'

#Devise for user authentication autherization
gem 'devise'

#Recaptcha !
gem "recaptcha", :require => "recaptcha/rails"

#Refinery for a wiki
#gem 'refinerycms', '~> 2.0.0'

gem 'hirb'

#Versioning
gem 'vestal_versions', :git => 'git://github.com/adamcooper/vestal_versions'

#slugifys and creates readable URLs
gem 'friendly_id'


gem 'delayed_job_active_record'

#replacing paperclip 
gem 'carrierwave'

#Newsfeed gem
gem 'public_activity'

#jquery gem for datepicker
gem 'jquery-ui-rails'

#gem for lightbox
gem 'facebox-rails'
gem 'kaminari'
